# ResolverBot - Node.js 22.14.0 (matches your local version)
FROM node:22.14.0-alpine

WORKDIR /app

# Install dependencies first (better layer cache)
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

# Copy application (.env excluded via .dockerignore; generated by docker-setup.sh)
COPY . .

EXPOSE 3000

CMD ["node", "index.js"]
