#!/usr/bin/env bash
# ResolverBot - Docker setup script
# Run: chmod +x docker-setup.sh && ./docker-setup.sh
# If Docker is not installed, the script will attempt to install it (Linux).

set -e

echo "=============================================="
echo "  ResolverBot - Docker Setup"
echo "=============================================="
echo ""

# --- Ensure Docker is installed ---
install_docker() {
  echo "Docker is not installed. Attempting to install..."
  if [ "$(uname -s)" = "Linux" ]; then
    if command -v curl &> /dev/null; then
      echo "Running official Docker install script (get.docker.com)..."
      sudo sh -c 'curl -fsSL https://get.docker.com | sh'
      echo "Starting Docker service..."
      sudo systemctl start docker 2>/dev/null || sudo service docker start 2>/dev/null || true
      sudo systemctl enable docker 2>/dev/null || true
      echo "Docker installed. You may need to log out and back in (or run: newgrp docker) to run docker without sudo."
      if ! groups | grep -q docker 2>/dev/null; then
        echo "Adding current user to 'docker' group..."
        sudo usermod -aG docker "$USER" 2>/dev/null || true
      fi
      return 0
    else
      echo "Error: curl is required to install Docker. Install curl and run this script again."
      return 1
    fi
  else
    echo "Error: Auto-install is supported only on Linux."
    echo "Please install Docker manually: https://docs.docker.com/get-docker/"
    return 1
  fi
}

if ! command -v docker &> /dev/null; then
  if ! install_docker; then
    exit 1
  fi
  echo "Please run this script again (or open a new terminal) so Docker is in PATH."
  exit 0
fi

if ! docker compose version &> /dev/null && ! docker-compose version &> /dev/null; then
  echo "Error: Docker Compose is not available."
  echo "On Linux, install the plugin: https://docs.docker.com/compose/install/"
  exit 1
fi

COMPOSE_CMD="docker compose"
if ! docker compose version &> /dev/null; then
  COMPOSE_CMD="docker-compose"
fi

# Create nginx dirs
mkdir -p docker/nginx/conf.d docker/nginx/ssl

# --- Webhook domain ---
read -p "Webhook domain (e.g. bot.example.com): " WEBHOOK_DOMAIN
WEBHOOK_DOMAIN=$(echo "$WEBHOOK_DOMAIN" | tr -d '[:space:]')
if [ -z "$WEBHOOK_DOMAIN" ]; then
  echo "Error: Webhook domain is required."
  exit 1
fi

# --- phpMyAdmin domain ---
read -p "phpMyAdmin domain (e.g. pma.example.com): " PMA_DOMAIN
PMA_DOMAIN=$(echo "$PMA_DOMAIN" | tr -d '[:space:]')
if [ -z "$PMA_DOMAIN" ]; then
  echo "Error: phpMyAdmin domain is required."
  exit 1
fi

# --- Bot token ---
read -p "Telegram bot token (BOT_TOKEN): " BOT_TOKEN
BOT_TOKEN=$(echo "$BOT_TOKEN" | tr -d '[:space:]')
if [ -z "$BOT_TOKEN" ]; then
  echo "Error: Bot token is required."
  exit 1
fi

# --- App port (internal) ---
read -p "Internal app port (default 3000): " APP_PORT
APP_PORT=${APP_PORT:-3000}
APP_PORT=$(echo "$APP_PORT" | tr -d '[:space:]')

# --- Bot name in start message ---
read -p "Bot name in start message (default: ResolverBot): " BOT_NAME
BOT_NAME=${BOT_NAME:-ResolverBot}
BOT_NAME=$(echo "$BOT_NAME" | tr -d '[:space:]')
[ -z "$BOT_NAME" ] && BOT_NAME="ResolverBot"

# --- First admin ---
read -p "First admin numeric ID: " ADMIN_FIRST
ADMIN_FIRST=$(echo "$ADMIN_FIRST" | tr -d '[:space:]')
if [ -z "$ADMIN_FIRST" ]; then
  echo "Error: At least one admin ID is required."
  exit 1
fi
ADMINS_LIST="$ADMIN_FIRST"

# --- More admins ---
while true; do
  read -p "Add another admin? (y/n): " MORE_ADMINS
  MORE_ADMINS=$(echo "$MORE_ADMINS" | tr '[:upper:]' '[:lower:]')
  if [ "$MORE_ADMINS" != "y" ] && [ "$MORE_ADMINS" != "yes" ]; then
    break
  fi
  read -p "Next admin numeric ID: " NEXT_ADMIN
  NEXT_ADMIN=$(echo "$NEXT_ADMIN" | tr -d '[:space:]')
  if [ -n "$NEXT_ADMIN" ]; then
    ADMINS_LIST="$ADMINS_LIST,$NEXT_ADMIN"
  fi
done

# --- Database password ---
read -sp "Database password (root & app): " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
  echo "Error: Database password is required."
  exit 1
fi

# --- WEBHOOK URL ---
WEBHOOK_URL="https://${WEBHOOK_DOMAIN}"
echo ""
echo "Webhook will be set to: $WEBHOOK_URL"
echo "If you only have HTTP for now, change WEBHOOK in .env to http://$WEBHOOK_DOMAIN later."
echo ""

# --- Write .env ---
cat > .env << ENVFILE
# ResolverBot - Generated by docker-setup.sh
BOT_TOKEN=$BOT_TOKEN
WEBHOOK=$WEBHOOK_URL
PORT=$APP_PORT
BOT_NAME=$BOT_NAME
ADMINS=$ADMINS_LIST

DB_HOST=db
DB_USER=root
DB_PASSWORD=$DB_PASSWORD
DB_NAME=resolverbot
DB_PORT=3306

REF_MONEY=0
ENVFILE

echo "Created .env"

# --- Write nginx config ---
NGINX_CONF="docker/nginx/conf.d/default.conf"
cat > "$NGINX_CONF" << NGINXFILE
# ResolverBot - Webhook + phpMyAdmin
# Generated by docker-setup.sh

# Bot webhook
server {
    listen 80;
    server_name $WEBHOOK_DOMAIN;
    location / {
        proxy_pass http://app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}

# phpMyAdmin
server {
    listen 80;
    server_name $PMA_DOMAIN;
    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINXFILE

echo "Wrote nginx config to $NGINX_CONF"

# --- Run Docker ---
echo ""
echo "Building and starting containers..."
$COMPOSE_CMD up -d --build

echo ""
echo "=============================================="
echo "  Setup complete"
echo "=============================================="
echo ""
echo "Webhook URL:  $WEBHOOK_URL/webhook"
echo "phpMyAdmin:   http://$PMA_DOMAIN"
echo ""
echo "Next steps:"
echo "  1) Point your domain DNS to this server's IP."
echo "  2) For HTTPS: get a certificate (e.g. certbot), enable it in nginx, set WEBHOOK=https://$WEBHOOK_DOMAIN in .env, then: $COMPOSE_CMD restart app"
echo "  3) Bot logs: $COMPOSE_CMD logs -f app"
echo ""
