CREATE DATABASE IF NOT EXISTS resolverbot;

USE resolverbot;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY,
  userID BIGINT UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255),
  balance BIGINT DEFAULT 0,
  refcode VARCHAR(6) UNIQUE,
  referredby BIGINT,
  ispremium BOOLEAN DEFAULT FALSE,
  datejoined DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_userID (userID),
  INDEX idx_refcode (refcode)
);

CREATE TABLE IF NOT EXISTS servers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  serverName VARCHAR(255) NOT NULL,
  serverIP VARCHAR(255) NOT NULL,
  serverDomain VARCHAR(255),
  port INT NOT NULL,
  serverPath VARCHAR(255),
  userName VARCHAR(255) NOT NULL,
  userPassword VARCHAR(255) NOT NULL,
  remark TEXT,
  isActive TINYINT(1) DEFAULT 1,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_isActive (isActive)
);

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name)
);

CREATE TABLE IF NOT EXISTS plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  volumeGB INT NOT NULL,
  durationDays INT NOT NULL,
  categoryId INT NOT NULL,
  serverId INT NOT NULL,
  inboundId VARCHAR(100) NOT NULL,
  inboundTag VARCHAR(255),
  capacityLimited TINYINT(1) NOT NULL DEFAULT 1,
  capacity INT NULL,
  priceToman BIGINT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_categoryId (categoryId),
  INDEX idx_serverId (serverId)
);
